### PR TITLE
Show all compatible wallets in the modal

### PR DESCRIPTION
**Pull request by ilanolkies**
This PR follows #138

It makes the initial modal bigger, showing all the compatible wallets. If the user does not pass a provider into the configuration it is greyed out.

I bumped to `v1.2.0-beta.1` to start promoting this cool version in our sample apps 😄 

Screen Shot 2021-09-06 at 01 34 43

### Implementation details

- The `Provider` component now gets a `width` from the modal, since there can be more than one per row. This is very bad for mobile. We should make it responsive.
- There is a `big` option for the `Modal` UI `big <=> currentStep === 'Step1'`. I didn't find a better way to make it
- I added `extraProviders.ts` with the logos and rest of the required info for showing them greyed out. It is a partial solution, maybe we can solve it in a more robust way.
- The big `max-width` is arbitrary, it makes all the providers fit ok

### CODE REVIEW

**Review by jessgusclark — CHANGES_REQUESTED** [review]
I'm not sure of the reasoning behind showing all the providers if they are not supported by the dapp. Anywho, with that said, there are a few usability issues:

1. The disabled class should have the normal cursor arrow, not the pointer. That way it doesn't look like it is clickable.

2. We lost the hover effect on the enabled items

3. on smaller screens, the layout should change, the items are squished and don't look well. Perhaps we can hide the disabled items to save space? 
 
Screen Shot 2021-09-06 at 2 34 07 PM

**Comment by ilanolkies** [comment]
1. and 2. perfect! I can add them
3. let's do another iteration for mobile. I open a new issue

**Comment by jessgusclark** [comment]
@ilanolkies You mentioned you were on holiday so I will take care of these items. For now here are is what needs to be done;

* [ ] disabled class, hover styles, 
* [ ] clean up the CSS to use flex only and not width/floats
* [ ] mobile: single column, hide wallet connect, and hardware wallets
* [ ] other providers from the developer not listed will not show up.

**Comment by ilanolkies** [comment]
@jessgusclark sure thanks!

**Review by jessgusclark — APPROVED** [review]

**Comment by jessgusclark** [comment]
@ilanolkies Please take a look at the additions I made. The comment above with checkboxes is a good summary, for more details, expand the commit comments. 

To test the developer providers, you can add Fortmatic to the index.html page like this:

```
<script src="https://unpkg.com/fortmatic@2.2.1/dist/fortmatic.js"></script>
```
and then later in the rLogin:
```
fortmatic: {
  package: Fortmatic,
  options: {
    key: "FORTMATIC_KEY"
  }
}
```

of course, it won't connect, but it will add it to the bottom row.

**Review by ilanolkies — COMMENTED** [review]
LRGTM!

**Pull request merged**
