### PR TITLE
Choose Dpath on Hardware Wallets

### PR DESCRIPTION
**Pull request by efucaraccio**
Branding Dpath table, path column was removed and a new column to identify the row was added.

### CODE REVIEW

**Review by ilanolkies — COMMENTED** [review]
Hi! How are you? We want to display the complete dpath, why do you need to change this? Please let us know your motivation for this change.

Also, we don't want to add `css-loader` to our build process. Please use existent `styled-components`

**Comment by ilanolkies** [comment]
@efucaraccio @jessgusclark what do you think about showing something like

| | Path | Address | Balance |
| - | - | - | - |
| 0 | m/44'/137'/0'/0/0 | 0xab...12 | 0.05 RBTC |
| 1 | m/44'/137'/0'/0/1 | 0xcd...12 | 0.02 RBTC |
| 2 | m/44'/137'/0'/0/2 | 0xfg...12 | 0.012 RBTC |

**Comment by efucaraccio** [comment]
Sorry, my bad. The suggested change isn't to remove dpath data but move it
at top just like this screenshot:
[image: image.png]

Update button would work just like the Select one allowing you to
select the account by dPath or selecting the row.
What do you think about it?

thank you very much for your patience

**Comment by jessgusclark** [comment]
@efucaraccio your image/screenshot did not post on the ticket.

**Comment by ilanolkies** [comment]
@efucaraccio any updates?

**Comment by jessgusclark** [comment]
I am going to close this PR due to inactivity. We can reopen when we have more information.

**Pull request closed without merging**
